### ISSUE TITLE
Jupyter notebook should be uploaded to the Code section of your repository.

### ISSUE THREAD

**Issue by luisortizuriarte** [istempko/clim680hw#2]
Jupyter notebook should be uploaded to the Code section of your repository. See github's documentation below:

https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository

**Comment by istempko** [comment]
I resubmitted this assignment in the Code section, so I was able to submit it as a .ipynb file.

**Comment by luisortizuriarte** [comment]
This has been fixed. Closed.
