### ISSUE TITLE
Different colormaps per panel

### ISSUE THREAD

**Issue by luisortizuriarte** [istempko/clim680hw#4]
Although you only have one colorbar for the figure, it is not representative of all your panels. You need to specify the color levels for each panel using the same values. See today's lesson on Composites for an example of how to specify contourf for your panels:

https://github.com/prukutu/clim680-codes/blob/gh-pages/src/Composites.ipynb

Right now, because you didn't specify them, your colorbar only corresponds to the most recently drawn figure.

**Comment by istempko** [comment]
I specified contourf for my panels like we did in the Composites lesson.

**Comment by luisortizuriarte** [comment]
Confirmed on the code. Closing issue.
